import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./_components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="px-20 my-[24px]">{children}</main>
      </body>
    </html>
  );
}
